version: 0.1

phases:
  build:
    commands:
      - ./gradlew
  post_build:
    commands:
      - curl -s https://raw.githubusercontent.com/stelligent/mu/master/install.sh | sh
      - mu -c banana-service/mu.yml svc push
