version: 0.1


phases:
  build:
    commands:
      - printenv
      - gradle build


artifacts:
  files:
    - banana-service/build/libs/*
    - banana-service/Dockerfile
    - banana-service/mu.yml
